### ISSUE TITLE
安装完成后无法下载文件？

### ISSUE THREAD

**Issue by balala8** [unknown-o/download-station#3]
大佬，请问为啥安装完成后无法下载文件。
点击下载文件出现文件不存在。
![无标题](https://user-images.githubusercontent.com/37032100/136971424-1f971887-6978-412e-afae-6cbe14af0c1e.png)

使用宝塔的一键安装的。
请问是哪里有问题？

**Comment by balala8** [comment]
刚刚的链接不对。是我自己输入的链接。这个是正常的截图。
![image](https://user-images.githubusercontent.com/37032100/136972226-db861d74-94e5-40af-8681-3b8bf40160e8.png)
突然发现readme.txt可以下载，但是图片依旧无法下载

**Comment by balala8** [comment]
又尝试了一下，图片后缀为JPG可以下载，如果是jpg，png则无法下载。
![image](https://user-images.githubusercontent.com/37032100/136972936-8b3c1a83-947a-40d5-b315-552fc2e18d4a.png)
请问这是为啥？

**Comment by X-system** [comment]
我的是超过100M就无法下载，任何文件类型都不行。

**Comment by unknown-o** [comment]
已经记录此问题。日后的更新中将修复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "unknown-o/download-station"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月13日(星期一) 凌晨4:42
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [unknown-o/download-station] 安装完成后无法下载文件？ (#3)





 
我的是超过100M就无法下载，任何文件类型都不行。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
